// src/components/editor/encodingDefinition.tsx
import { useUmweltSpec } from '../../contexts/UmweltSpecContext';
import { EncodingFieldDef, EncodingPropName, audioPropNames, visualPropNames } from '../../types';
import { describeField } from '../../util/description';
import { FieldTransforms } from './fieldTransforms';

export type EncodingDefinitionProps = {
  unit: string;
  property: EncodingPropName;
  encoding: EncodingFieldDef;
};

export function EncodingDefinition({ unit, property, encoding }: EncodingDefinitionProps) {
  const [spec, specActions] = useUmweltSpec();

  return (
    <div>
      <h5>{property}</h5>
      <div>
        <select
          value={encoding.field}
          onChange={(e) => {
            specActions.removeEncoding(encoding.field, property, unit);
            specActions.addEncoding(e.currentTarget.value, property, unit);
          }}
        >
          {spec.fields
            .filter((f) => f.active)
            .map((field) => {
              return (
                <option value={field.name} selected={encoding.field === field.name}>
                  {field.name}
                </option>
              );
            })}
        </select>
        <button
          onClick={() => {
            specActions.removeEncoding(encoding.field, property, unit);
          }}
        >
          Remove encoding
        </button>
        <FieldTransforms fieldName={encoding.field} encoding={{ unit, property }} />
      </div>
    </div>
  );
}

// packages/umwelt-solid/src/components/editor/encodingDefinition.tsx
import { For } from 'solid-js';
import { useUmweltSpec } from '../../contexts/UmweltSpecContext';
import { EncodingFieldDef, EncodingPropName } from '../../types';
import { FieldTransforms } from './fieldTransforms';
import { styled } from 'solid-styled-components';
import { EncodingContainer, EncodingColumn, EncodingRow } from '../ui/styled';

export type EncodingDefinitionProps = {
  unit: string;
  property: EncodingPropName;
  encoding: EncodingFieldDef;
};


export function EncodingDefinition(props: EncodingDefinitionProps) {
  const [spec, specActions] = useUmweltSpec();

  return (
    <EncodingContainer>
      <h5>{props.property}</h5>
      <EncodingColumn>
        <EncodingRow>
          <select
            value={props.encoding.field}
            onChange={(e) => {
              specActions.removeEncoding(props.encoding.field, props.property, props.unit);
              specActions.addEncoding(e.currentTarget.value, props.property, props.unit);
            }}
          >
            <For each={spec.fields.filter((f) => f.active)}>
              {(field) => (
                <option value={field.name} selected={props.encoding.field === field.name}>
                  {field.name}
                </option>
              )}
            </For>
          </select>
          <button
            onClick={() => {
              specActions.removeEncoding(props.encoding.field, props.property, props.unit);
            }}
          >
            Remove encoding
          </button>
        </EncodingRow>
        <FieldTransforms fieldName={props.encoding.field} encoding={{ unit: props.unit, property: props.property }} />
      </EncodingColumn>
    </EncodingContainer>
  );
}
